site_name: Expresión Gráfica
copyright: Copyright &copy; 2025 Alberto Durán Pérez
theme:
  name: material
  language: es
  font:
    text: Lato, sans-serif
    code: Fira code, sans-serif

  palette: 
      # Modo claro
      - scheme: default
        primary: indigo
        accent: red
        toggle:
          icon: material/brightness-7
          name: Cambiar a modo oscuro
      
      # Modo oscuro  
      - scheme: slate
        primary: indigo
        accent: red
        toggle:
          icon: material/brightness-4
          name: Cambiar a modo claro
  
  icon:
    logo: material/pencil-ruler
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle
  features:
    - navigation.sections
     #- navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.breadcrumbs
    - navigation.search
    - navigation.sitemap
    - navigation.indexes
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - search.highlight
    - search.suggest
    - search.share
    - content.code.annotate
    - content.tabs
    - content.tooltips
    - content.images
    - content.captions
    - content.emoji
    - content.math
    - content.video
    - content.audio
    - content.details
    - content.admonition
    - content.code.copy
    - content.code.annotate
    - toc.integrate
    - toc.sticky
    - header.autohide
    - footer.social
    - footer.previous-next
    - footer.edit-link
    - footer.legal

repo_url: https://citius70.github.io/expresion_grafica_tecnologia_1eso/
repo_name: expresion_grafica_tecnologia_1eso
# site_description: "Expresión Gráfica - Tecnología y digitalización - 1º ESO"
# site_author: Alberto Durán Pérez




copyright: Alberto Durán Pérez - Departamento de Tecnología - IES Frei Martín Sarmiento (Pontevedra)

nav:
  - Inicio: index.md
  - 1️⃣ La tecnología y el dibujo: 1_tecnologia_dibujo.md
  -    ❔ Autoevaluación: ejercicios/tecnologia_ejercicios.md
  - 2️⃣ Del boceto al croquis: 2_boceto.md
  -    ❔ Autoevaluación: ejercicios/boceto_ejercicios.md
  - 3️⃣ El plano: 3_plano.md
  - 4️⃣ Instrumentos de dibujo técnico: 4_instrumento.md
  - 5️⃣ Las vistas de un objeto (Sistema Diédrico): 
      - 5️⃣.1️⃣ Introducción a las vistas: 5_vistas.md
      - 5️⃣.2️⃣ Las tres vistas principales: 5_1_vistas_tres.md
      - 5️⃣.3️⃣ Las seis vistas de un objeto: 5_2_vistas_seis.md
  - 6️⃣ La acotación (poniendo las medidas): 6_acotacion.md
  - 7️⃣ Dibujo asistido por ordenador (CAD): 7_librecad.md
  - 📄(Documento en PDF): pdf/document.pdf

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  # - toc:
  #   permalink: true
  # - smarty  
  # - abbr
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - js/quiz.js
  - js/cuestionario-generico.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - css/quiz.css
  - css/cuestionarios.css
  # - css/pdf_style.css
  - assets/fonts.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://citius70.github.io/expresion_grafica_tecnologia_1eso/1_tecnologia_dibujo/
      name: Repositorio GitHub
  analytics: 
    feedback:
      title: ¿Te fue de ayuda esta página?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Esta página fue útil
          data: 1
          note: >-
            ¡Gracias por tu comentario!
        - icon: material/emoticon-sad-outline
          name: Esta página podría mejorarse
          data: 0
          note: >- 
            ¡Gracias por tu comentario! Ayúdanos a mejorar esta página
            utilizando nuestro <a href="..." target="_blank" rel="noopener">formulario de comentarios</a>.

plugins:
  - search:
      lang: es
      separator: '[\s\-]+'
  - with-pdf:
      cover: true
      cover_title: "Expresión gráfica"
      cover_subtitle: "Tecnología y digitalización - 1º ESO"
      author: "Alberto Durán Pérez"
      subject: "Teoría"
      affiliation: "IES Frei Martín Sarmiento - Pontevedra"
      enabled_if_env: ENABLE_PDF_EXPORT
      output_path: pdf/document.pdf
      
      # ESTA es la configuración que funciona para CSS
      extra_css:
        - css/pdf_fixes.css
      
      # Fuentes para el motor de PDF
      font:
        base: "Arial"
        code: "Courier New"
        size: 11
      
      # Metadata importante
      encoding: "utf-8"
      quality: 100
      
      toc:
        enabled: true
        depth: 2
      
      number_sections: true
      orientation: portrait
      
      margin:
        top: 15
        bottom: 15
        left: 15
        right: 15